import { format } from 'date-fns'

interface ReadmeInput {
  user: {
    email: string
    currency: string
    timezone: string
  }
  statistics: {
    transactions: number
    budgets: number
    goals: number
    accounts: number
    recurringTransactions: number
    categories: number
  }
  dateRange: {
    earliest: Date
    latest: Date
  } | null
  exportedAt: Date
}

export function generateReadme(input: ReadmeInput): string {
  const exportDate = format(input.exportedAt, 'MMMM d, yyyy \'at\' h:mm a')
  const dateRangeText = input.dateRange
    ? `${format(input.dateRange.earliest, 'MMMM d, yyyy')} to ${format(input.dateRange.latest, 'MMMM d, yyyy')}`
    : 'All time'

  return `# Wealth Export Package

## Export Information

- **Exported by:** ${input.user.email}
- **Export date:** ${exportDate}
- **Date range:** ${dateRangeText}
- **Currency:** ${input.user.currency}
- **Timezone:** ${input.user.timezone}

## Contents

This export package contains your complete financial data in multiple formats:

### Data Files

1. **transactions.csv** - ${input.statistics.transactions} transaction records
   - Date, payee, amount, category, account, tags, notes

2. **budgets.csv** - ${input.statistics.budgets} budget records
   - Month, category, budgeted amount, spent amount, remaining, status

3. **goals.csv** - ${input.statistics.goals} financial goal records
   - Goal name, target/current amounts, progress %, target date, status

4. **accounts.csv** - ${input.statistics.accounts} account records
   - Account name, type, balance, connection status, last updated

5. **recurring-transactions.csv** - ${input.statistics.recurringTransactions} recurring transaction records
   - Payee, amount, frequency, next scheduled date, status

6. **categories.csv** - ${input.statistics.categories} category records
   - Category name, parent category, icon, color, type

### Metadata Files

- **summary.json** - Export statistics and metadata
- **ai-context.json** - AI-friendly field descriptions and analysis prompts

## File Formats

All CSV files use:
- UTF-8 encoding with BOM (opens correctly in Excel)
- ISO 8601 date format (YYYY-MM-DD)
- Comma-separated values with quoted strings
- Amounts in ${input.user.currency} with 2 decimal places

## Using This Data

### Spreadsheet Analysis

Open any CSV file in:
- Microsoft Excel (2016 or later)
- Google Sheets
- Apple Numbers
- LibreOffice Calc

All files will display correctly with proper character encoding.

### AI-Powered Analysis

Use the \`ai-context.json\` file with AI tools like ChatGPT or Claude:

1. Upload all CSV files to the AI chat
2. Include \`ai-context.json\` for context
3. Try these prompts:
   - "Analyze my spending patterns and suggest ways to save money"
   - "Review my budget adherence and recommend adjustments"
   - "Check if I'm on track to meet my financial goals"
   - "Find unnecessary recurring subscriptions I can cancel"

The AI context file includes detailed field descriptions and pre-written prompts.

### Programming & Scripts

All data is in standard formats for easy parsing:
- Python: \`pandas.read_csv('transactions.csv')\`
- JavaScript: Parse CSV with \`papaparse\` or similar
- R: \`read.csv('transactions.csv')\`

The \`summary.json\` file provides metadata for programmatic access.

## Data Privacy

This export contains sensitive financial information:
- Store securely (encrypted drive, password-protected folder)
- Do not share publicly or via unencrypted email
- Delete from downloads folder after use
- Keep only on devices you trust

**Note:** Sensitive tokens like Plaid access tokens are automatically redacted from exports.

## Support

For questions or issues with your export:
- Visit the Wealth app settings
- Contact support through the help center
- Email: support@wealth-app.com

---

**Export Version:** 1.0
**Generated by:** Wealth Financial Management App
**Expires:** This export is valid for 30 days from the export date.
`
}
